# Generated by Django 4.0.6 on 2022-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_director_film'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='date_release',
            field=models.DateField(blank=True, help_text='Fecha de estreno', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.TextField(help_text='Sinopsis de la película', max_length=255),
        ),
    ]
