# Generated by Django 4.0.6 on 2022-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_film_year_film_date_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='synopsis',
            field=models.TextField(help_text='Sinopsis de la película', max_length=500),
        ),
    ]
